name: girls_agent_app
description: App for girls agent

publish_to: "none"

version: 1.0.1+269

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.3
  app_tracking_transparency: ^2.0.2+1
  google_mobile_ads: ^1.0.1
  sqflite: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_no_background.png
    - assets/material_design_3.png
    - assets/material_design_4.jpg

flutter_intl:
  enabled: true
