// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxplp1LDxZPdCZAXydSxcUvs_2nDd133k',
    appId: '1:544226714903:android:b20a8a81709bdfbc7ac352',
    messagingSenderId: '544226714903',
    projectId: 'argon-jetty-342517',
    storageBucket: 'argon-jetty-342517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIO-5p_wjdKLAVHYWHAKMuGwfhiM3j3Q',
    appId: '1:544226714903:ios:6af32f32c54821f77ac352',
    messagingSenderId: '544226714903',
    projectId: 'argon-jetty-342517',
    storageBucket: 'argon-jetty-342517.appspot.com',
    iosClientId: '544226714903-8ud4lahj3mhlhhaunbcdodevl8k09r9s.apps.googleusercontent.com',
    iosBundleId: 'com.tocandraw.girlsAgentApp',
  );
}
