// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6AcSHsTFi1HN5ROU8SqAAOkVVbM7H1I',
    appId: '1:1039971329499:android:5604c0049175afe15233fe',
    messagingSenderId: '1039971329499',
    projectId: 'girlsagentapp',
    storageBucket: 'girlsagentapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLyTNZR1jYbgItSnNI8HaDQcU7LPR9vc',
    appId: '1:1039971329499:ios:018c609e138a1d535233fe',
    messagingSenderId: '1039971329499',
    projectId: 'girlsagentapp',
    storageBucket: 'girlsagentapp.appspot.com',
    iosClientId: '1039971329499-9a7bk91edcfb6vuugpade872qu5q487c.apps.googleusercontent.com',
    iosBundleId: 'com.tocandraw.girlsAgentApp',
  );
}
